"Code Injection set up" guide
ds-pokemon-hacking/ds-pokemon-hacking.github.io pull request #47
Opened 2024-05-29 00:09 UTC by Paideieitor

# Name of Resource
Code Injection set up

# Description
Guide to set up a Code Injection environment in Windows with Visual Studio

# Which Generation (4/5/Universal)?
Gen 5 B2W2

# Notes
It has a tutorial at the end to create a test patch

2024-06-01 11:59 UTC, HelloOO7 requested changes
IMO this is a really well-made guide.
I added some remarks about the file organization and a couple of mistakes (some more important than others - please fix the `-Os`!) but as far as the content is concerned this seems good to go.

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +This is a practical guide so it doesn't stop to explain the reason behind the steps, it is NOT a replacement for the [Code Injection guide](https://ds-pokemon-hacking.github.io/docs/generation-v/guid
Local links should be relative (../../bw_b2w2-code_injection/)

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +4. Go to https://github.com/HelloOO7/NitroKernel and download the code as a ZIP file
This is probably fine, but it should be noted that a lot of NK's functionality depends (in one way or another) on extlib (memory management) or libRPM (executable/library framework) and using the sources this way will lead to compilation errors further down the way if one chooses to include certain other NK files.

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +6. move the ``kenel`` folder to ``CodeInjection/PW2Code/Headers``
~~kenel~~ kernel

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +      - ext_lib
Afaik this is not a part of the swan headers - may have been forgotten to be mentioned somewhere?

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +5. Extract the files and rename the ``include`` folder to ``kernel``
This is really not pretty. Not that it's a cardinal sin or anything, but it could be done in a less hacky way. I'm talking mainly of cases where swan headers are cloned from git and kept updated (using git pull) - cluttering that folder with NK includes will make this tedious.

I would generally recommend to use "git clone" for dependencies where possible as opposed to downloading sources as zips.

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +8. Before going to the next section go to the ``k_Print.h`` file in Visual Studio and add ``#include <cstdarg>`` before ``#include "k_DllExport.h"`` (this fixes issues when using the print functions
~~k_Print.h~~ kPrint.h

k_# files are for internal NK use, k# are API.

Furthermore, this seems to be a problem with NK, so it would be better if it was fixed as such instead of adding workarounds to the guide. If that's the case I'll fix it in the NK repo. (which further serves as an argument for cloning NK sources using Git instead of downloading them as zips)

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> + - IDA Pro (you can also use Ghydra)
~~Ghydra~~ Ghidra

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +Make sure all your functions are in between *C_DECL_BEGIN* and *C_DECL_END*, you can add *C_DECL_BEGIN* at the begining of your files and *C_DECL_END* at the end and forget about it (you will need to
Better to use `extern "C" void func();` or `extern "C" { <declarations> }`.
C_DECL_BEGIN and C_DECL_END are macros made for use by SwanComposer and they only really exist so that `extern "C"` is omitted when using C (as opposed to C++). Since this tutorial focuses on C++, the macros only cause confusion in my opinion.

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +2. We need to tell CTRMap that this function is overriding another one so we use a "tag" before the function name, in this case "THUMB_BRANCH" -> ``THUMB_BRANCH_BagSave_AddItemCore`` (for more info o
dtto about relative links

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +6. Eventhough ``BagItem`` is also a pointer we do use it as a struct so we need to declare it and define it:
~~Eventhough~~ Even though

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +7. The function uses a function called "BagSave_GetItemHandleAddCheck" we can double click it in IDA to get de declaration -> ``BagItem * BagSave_GetItemHandleAddCheck(BagSaveData *bag, u16 item_idx,
~~de~~ the declaration

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +9. Finally we want to print a console message (this is very usefull since we can't use breakpoints):
~~usefull~~ useful

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +This instructions asume you followed the previous steps, your SWAN headers are in the ``CodeInjection/PW2Code/Headers`` folder and your code in the ``CodeInjection/PW2Code/Patches`` folder.
~~This instructions asume~~ These instructions assume

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +"-Os" is the patch file
`-Os` is the optimization level!

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +I recomend that you set the output file to be in a specific folder for the elf files, to keep stuff organized.
~~recomend~~ recommend

2024-06-01 11:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +Once you have the correct ESDB follow this steps:
~~this~~ these

2024-06-03 05:41 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +This is a practical guide so it doesn't stop to explain the reason behind the steps, it is NOT a replacement for the [Code Injection guide](https://ds-pokemon-hacking.github.io/docs/generation-v/guid
done

2024-06-03 05:43 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +      - ext_lib
fixed

2024-06-03 05:43 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +5. Extract the files and rename the ``include`` folder to ``kernel``
I changed the "File structure" section to include both SWAN and NitroKernel as separate External Dependences

2024-06-03 05:43 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +6. move the ``kenel`` folder to ``CodeInjection/PW2Code/Headers``
fixed

2024-06-03 05:44 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +9. Finally we want to print a console message (this is very usefull since we can't use breakpoints):
fixed

2024-06-03 05:44 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +This instructions asume you followed the previous steps, your SWAN headers are in the ``CodeInjection/PW2Code/Headers`` folder and your code in the ``CodeInjection/PW2Code/Patches`` folder.
fixed

2024-06-03 05:44 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +"-Os" is the patch file
fixed this section

2024-06-03 05:44 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +I recomend that you set the output file to be in a specific folder for the elf files, to keep stuff organized.
fixed

2024-06-03 05:44 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +Once you have the correct ESDB follow this steps:
fixed

2024-06-03 05:48 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +4. Go to https://github.com/HelloOO7/NitroKernel and download the code as a ZIP file
I don't have much experience with NitroKernel since I have only used it for Debug Printing. How would you approach this part of the guide? Keep in mind this section was updated to conform to a note further down and I don't know how that affects this note.

2024-06-03 07:59 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +4. Go to https://github.com/HelloOO7/NitroKernel and download the code as a ZIP file
This is but one of many approaches, but you could create a "dependencies" or "externals" folder and inside it clone NK, swan, libRPM and extlib next to each other. They should recognize themselves mutually if placed like that.

2024-06-03 08:05 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +5. Extract the files and rename the ``include`` folder to ``kernel``
Seems alright, although the folder listing looks a bit suspicious. It might be just a tab/space rendering issue on Github's part though.

2024-06-03 17:39 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +4. Go to https://github.com/HelloOO7/NitroKernel and download the code as a ZIP file
I can only clone a repository in an empty folder so there needs to be a "dummy forlder" for each repo (SWAN/swan). Do you know any work around or is this approach fine (if I include libRPM & extlib)?

2024-06-03 18:48 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +4. Go to https://github.com/HelloOO7/NitroKernel and download the code as a ZIP file
I changed the File Structure to include swan, NK, ExtLib and libRPM inside an ExternalDependencies folder

2024-06-03 20:28 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +4. Go to https://github.com/HelloOO7/NitroKernel and download the code as a ZIP file
Looks OK!

2024-06-04 00:24 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +8. Before going to the next section go to the ``k_Print.h`` file in Visual Studio and add ``#include <cstdarg>`` before ``#include "k_DllExport.h"`` (this fixes issues when using the print functions
Fixed, this step is no longer in the guide. However, I have added a step to include the dependency before including kPrint. Do you want me to keep it until it is fixed in NK or should I take it out?

2024-06-04 19:40 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +8. Before going to the next section go to the ``k_Print.h`` file in Visual Studio and add ``#include <cstdarg>`` before ``#include "k_DllExport.h"`` (this fixes issues when using the print functions
I've fixed the issue in NK commit `4beeba2`, so you can feel free to remove it. Thanks for the report, by the way.
Since it's just a source code header fix there is no need to update NK itself, as it has no impact on the resulting binary.

2024-06-04 20:59 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +8. Before going to the next section go to the ``k_Print.h`` file in Visual Studio and add ``#include <cstdarg>`` before ``#include "k_DllExport.h"`` (this fixes issues when using the print functions
nice

2024-06-04 21:02 UTC, Paideieitor commented
Ok, if I didn't forget anything all requested changes should be fixed now.

2024-06-04 21:07 UTC, HelloOO7 approved these changes

2024-06-04 21:10 UTC, HelloOO7 commented
As far as I'm concerned this is fit to be merged.

2024-06-06 03:05 UTC, PlatinumMaster approved these changes
I think this is a good start for the guide. There's a few touchups which I'd recommend (left a few comments), and it may be something we'd want to expand on in the future.

2024-06-06 03:05 UTC, PlatinumMaster commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> + - IDA Pro (you can also use Ghidra)
Minor nitpick: any disassembler works. Just explain the reasoning why.

2024-06-06 03:05 UTC, PlatinumMaster commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +```
You can use syntax highlighting here, like so:
\`\`\`cpp
code goes here
\`\`\`

2024-06-06 03:05 UTC, PlatinumMaster commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +### IDB research
This section is good, but could benefit from a scenario where you want to research a new overlay (since this is commonly asked).

2024-06-06 03:05 UTC, PlatinumMaster commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +```
Syntax highlighting here also.

2024-06-06 03:05 UTC, PlatinumMaster commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +These instructions assume you followed the previous steps, your SWAN headers and other External Dependencies are in the ``CodeInjection/PW2Code/ExternalDependencies`` folder and your code in the ``Co
So while this method is the recommended way, you should explain how the include paths work, since that is fundamental knowledge if someone does not use Visual Studio.

2024-06-06 10:50 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +These instructions assume you followed the previous steps, your SWAN headers and other External Dependencies are in the ``CodeInjection/PW2Code/ExternalDependencies`` folder and your code in the ``Co
I added some extra context about Additional Include Directories in this section, is it well explained?

2024-06-06 10:58 UTC, Paideieitor commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +### IDB research
I am completely unknowledgeable in this topic. However, since this guide is targeted to beginners, especially those without much general knowledge, this really simple example might be enough. I feel that IDB research is so vast it could be a guide of its own. Eitherway if you know any resource so I can learn about this it'd be great.

2024-06-06 14:01 UTC, HelloOO7 commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +### IDB research
I agree that this guide in its nature is more of an Arduino-ish "code injection 101 starter tutorial" and that low-level research is out of its scope. It could, however, be handy to add a link to the main code injection tutorial, which does have a section that concerns making custom ESDBs from .map files, and mention that only the ESDB is what's actually needed (as opposed to the whole IDB).

2024-06-07 04:56 UTC, PlatinumMaster commented on docs/generation-v/guides/b2w2-code_injection_set_up/b2w2-code_injection_set_up.md
> +### IDB research
Fair enough; I mainly meant in terms of future expansion (which is why I approved the commits otherwise). But we can cross that bridge when we get there.

2024-06-07 04:57 UTC, merged